[package]
name = "rime-tool"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/Yiklek/RimeTool"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "~0.24"
log = "~0.4"
log4rs = { version = "~1.2", features = ["toml_format"]}
once_cell = "~1.18"
registry = "~1.2"
serde = "~1"
serde_yaml = "~0.9"
sysinfo = "~0.29"
tao = "~0.22"
toml = "~0.8"
tray-icon = "~0.9"

[target.'cfg(windows)'.dependencies]
registry = "~1.2"


[target.'cfg(windows)'.build-dependencies]
winres = "*"
